version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: escola
    volumes:
          - ./escola.sql:/docker-entrypoint-initdb.d/escola.sql
    ports: 
          - "5432:5432"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports: 
          - "15432:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge